### ISSUE TITLE
Add support of categorical features of types int and bool

### ISSUE THREAD

**Issue by MainRo** [interpretml/ebm2onnx#1]
* ebm2onnx version: 1.1.0
* Python version: 3.7
* Operating System: Linux

### Description

Currently, the categorical features are supported only for string types. We should also support int and booleans as categorical features. For these types, no CategoricalMapper is needed.

**Comment by Hoeze** [comment]
I just ran into that issue.

**Comment by MainRo** [comment]
I have several evolutions planned to support the upcoming interpret release.
I will see if I can add this support before.

**Comment by Hoeze** [comment]
Thanks a lot @MainRo!
