### ISSUE TITLE
Explanations from ONNX Model Object

### ISSUE THREAD

**Issue by ReneeErnst** [interpretml/ebm2onnx#10]
* ebm2onnx version: 3.1.1
* Python version: 3.9
* Operating System: Ubuntu

### Description

This is a question that depending on the answer is also a request to update docs or add functionality. I was looking at the [explain_local.ipynb ](https://github.com/interpretml/ebm2onnx/blob/master/examples/explain_local.ipynb). The examle showing local explanations uses the original ebm model object, pre onnx conversion. 

My question - is it posible to get the local explanations directly from the onnx model object? If so, an update to that notebook would be awesome. If not - is this possible to add? I'll of course dig into the code more and test it out (haven't found anything that indicates this will work yet), but want to raise this here since either way the question results in a requested update. 

My reasoning is that I'm using onnx model objects in production, when I no longer have the original trained model object (pre onnx conversion) available. I'm currently using a sklearn logistic regression, but am looking to transitioning to an EBM model as long as we can maintain all functionality and use ONNX as opposed to pickle serialization. When we generate predictions we output explainability/feature impact data. I need to make sure we'd be able to do this with the EBM model converted to ONNX as well.

**Comment by ReneeErnst** [comment]
Sorry for this - I see now that the last step in that notebook does point on that the onnx prediction includes the local explanations! Closing this issue.

**Comment by ReneeErnst** [comment]
Sorry for this - I see now that the last step in that notebook does point on that the onnx prediction includes the local explanations! Closing this issue.

**Comment by MainRo** [comment]
yes, you can use the _explain_ parameter to get the local explanations (the terms scores) from the onnx model:
https://ebm2onnx.readthedocs.io/en/latest/reference.html#ebm2onnx.to_onnx

**Comment by ReneeErnst** [comment]
Thanks! Sorry for the miss on my part!
