### ISSUE TITLE
Scoring Spark DataFrames

### ISSUE THREAD

**Issue by brandongreenwell-8451** [interpretml/ebm2onnx#7]
* ebm2onnx version: 2.0.0
* Python version: 3.8
* Operating System: Azure/databricks

### Description

From what I understand, [synapseML](https://microsoft.github.io/SynapseML/docs/next/features/onnx/about/) includes a Spark transformer to bring a trained ONNX model to Apache Spark. Has anyone attempted or had success in getting this to work with an EMB stored in ONNX format?

**Comment by brandongreenwell-8451** [comment]
I'll work on posting a small reproducible example to help.

**Comment by MainRo** [comment]
Can I close the issue now that https://github.com/microsoft/SynapseML/issues/1902 is fixed?
